# Generated by Django 5.2.5 on 2025-10-31 06:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_favorites'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('house', 'House'), ('plot', 'Plot'), ('apartment', 'Apartment'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=50, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=50, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('min_bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this alert active?')),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now, help_text='When the alert was last run.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
