# Generated by Django 5.2.5 on 2025-11-13 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_agentrating'),
        ('properties', '0006_property_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(help_text="The lead's full name (e.g., Ali Khan)", max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow-up'), ('visit_scheduled', 'Visit Scheduled'), ('not_interested', 'Not Interested'), ('closed', 'Closed')], default='new', help_text='The current stage of this lead in the sales pipeline.', max_length=20)),
                ('source', models.CharField(blank=True, help_text="Where this lead came from (e.g., 'PropWise Chat', 'Phone Call')", max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text="Agent's private notes about this lead.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text='The agent this lead belongs to.', limit_choices_to={'is_agent': True}, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('property_of_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
