# Generated by Django 5.2.5 on 2025-11-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Mark this listing as verified by the admin (e.g., checked for accuracy).'),
        ),
    ]
