# Generated by Django 5.2.5 on 2025-11-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured_until',
            field=models.DateTimeField(blank=True, help_text='When this listing should stop being featured (e.g., 7 days from now).', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Mark this listing as 'Featured' to show it at the top."),
        ),
    ]
