# Generated by Django 5.2.5 on 2025-11-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_featured_until_property_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sold_date',
            field=models.DateTimeField(blank=True, help_text='The date and time this property was marked as sold.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired')], default='active', help_text='The current status of the listing (e.g., Active, Sold).', max_length=10),
        ),
    ]
