# Generated by Django 5.2.5 on 2025-11-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_sold_date_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, help_text='A link to a YouTube or Vimeo video walkthrough (e.g., https://www.youtube.com/watch?v=...)', max_length=500, null=True),
        ),
    ]
