# Generated by Django 5.2.5 on 2025-11-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the neighborhood (e.g., amenities, lifestyle).', null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for the map (e.g., 31.470510)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for the map (e.g., 74.394170)', max_digits=9, null=True),
        ),
    ]
