# Generated by Django 5.2.5 on 2025-11-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_area_description_area_latitude_area_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Beaconhouse School' or 'Green Valley Supermarket'", max_length=255)),
                ('amenity_type', models.CharField(choices=[('school', 'School'), ('hospital', 'Hospital'), ('park', 'Park'), ('restaurant', 'Restaurant'), ('supermarket', 'Supermarket'), ('other', 'Other')], default='other', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text="Optional: Latitude for this amenity's map pin", max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text="Optional: Longitude for this amenity's map pin", max_digits=9, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='locations.area')),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['amenity_type', 'name'],
            },
        ),
    ]
